baseURL: https://shubozhang.github.io
languageCode: en-us
title: Shubo Zhang
theme: "toha"


# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
googleAnalytics: UA-123-45

# Enable Disqus forum
disqusShortname: shubozhang

# Enable global emoji support
enableEmoji: true

# Site parameters
Params:
  # Copyright Notice
  copyright: © 2020 Copyright.

  # Meta description for my site.  This will help the search engines to find my site.
  description: Shubo Zhang site for hugo theme Toha.

  # Background image of the landing page
  background: "images/site/programming-world-map.png"

  # Provide logos for my site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will default to the theme logos if not provided.
  logo:
    main: images/logos/toha.png
    inverted: images/logos/logo-inverted.png
    favicon: images/logos/favicon.png

  # GitHub repo URL of my site
  gitRepo: https://github.com/shubozhang/shubozhang.github.io

  # specify whether I want to write some blog posts or not
  enableBlogPost: true

  # specify whether I want to show Table of Contents in reading page
  enableTOC: true

  # specify the list of custom menus that I want to show in the top navbar.
  # they will be separated by a divider from the main menus.
#   customMenus:
#   - name: Notes
#     url: https://hossainemruz.gitbook.io/notes/

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, I can just hide it from the footer.
  newsletter:
    enable: true
